global:
  scrape_interval: 1s
  scrape_timeout: 1s

scrape_configs:
  - job_name: 'jrpk-server'
    static_configs:
      - targets:
          - 'jrpk:1134'
  - job_name: 'jrpk-client'
    honor_labels: true
    static_configs:
      - targets:
          - 'pmg:9091'